### ISSUE TITLE
Show me password stopped working in SQL Developer 18.3

### ISSUE THREAD

**Issue by heklaz** [tomecode/show-me-password-sqldev-jdev#15]
After upgrading to 18.3 it seems that "Show me password" doesn't work any longer.

It show in the file-menu but nothing happens when selecting it.

It has worked until and including SQL Developer 18.2.

Version: ShowMePasswordSQLDeveloper4-17_v1.1.0

Very nice utility :-)

Regards

**Comment by jpvadell** [comment]
Yes, I had the same problem. This is the error. 

Exception while performing action Show Me Password
java.lang.NoClassDefFoundError: oracle/jdevimpl/db/adapter/DefaultContextWrapper
	at com.tomecode.showme.password.sqldeveloper.SQLDeveloperConnectionsParser.loadDbConfig(SQLDeveloperConnectionsParser.java:43)
	at com.tomecode.showme.password.sqldeveloper.ShowMePasswordController.handleEvent(ShowMePasswordController.java:31)
	at oracle.ideimpl.controller.MetaClassController.handleEvent(MetaClassController.java:52)
	at oracle.ide.controller.IdeAction$ControllerDelegatingController.handleEvent(IdeAction.java:1488)
	at oracle.ide.controller.IdeAction.performAction(IdeAction.java:663)
	at oracle.ide.controller.IdeAction.actionPerformedImpl(IdeAction.java:1159)
	at oracle.ide.controller.IdeAction.actionPerformed(IdeAction.java:618)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at oracle.javatools.internal.ui.EventQueueWrapper._dispatchEvent(EventQueueWrapper.java:169)
	at oracle.javatools.internal.ui.EventQueueWrapper.dispatchEvent(EventQueueWrapper.java:151)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: oracle.jdevimpl.db.adapter.DefaultContextWrapper cannot be found by com.tomecode.showme.password.sqldeveloper_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at org.netbeans.modules.netbinox.NetbinoxLoader.loadClass(NetbinoxLoader.java:81)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more

**Comment by tomecode** [comment]
fixed in #16 - release: [Show Me Password for SQL Developer (version: 18)
](https://github.com/tomecode/show-me-password-sqldev-jdev/releases/download/%2316/ShowMePasswordSQLDeveloper-18c_v2.0.0.zip)

**Comment by heklaz** [comment]
Works again :-)
Thanks a lot.

**Comment by JIng1es** [comment]
@tomecode Are there plans to update the utility to work with SQL Developer 19.2?

**Comment by tomecode** [comment]
it should also work for SQL Developer 19.2

**Comment by pradhyu** [comment]
> it should also work for SQL Developer 19.x

didn't work for  Version 19.2.1.247.
